name:                telethenticateApi
version:             0.1.0.0
github:              "githubuser/telethenticateApi"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/telethenticateApi#readme>

dependencies:
- base >= 4.7 && < 5
- servant-server
- persistent
- persistent-postgresql
- warp
- aeson
- wai
- safe
- mtl
- persistent-template
- text
- monad-logger
- servant-auth
- bcrypt
- bytestring
- servant-auth-server
- jose
- time

library:
  source-dirs: src

executables:
  telethenticateApi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telethenticateApi

tests:
  telethenticateApi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telethenticateApi
