name:                servantStarter
version:             0.1.0.0
github:              "githubuser/servant-jwt-starter"
license:             BSD3
author:              "Josh"
maintainer:          "example@example.com"
copyright:           "2018 Josh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/servant-jwt-starter#readme>

dependencies:
- base >= 4.7 && < 5
- servant-server
- persistent
- persistent-postgresql
- warp
- aeson
- wai
- safe
- mtl
- persistent-template
- text
- monad-logger
- servant-auth
- bcrypt
- bytestring
- servant-auth-server
- jose
- time
- foreign-store
- katip
- fast-logger
- resource-pool

library:
  source-dirs: src

executables:
  servantStarter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servantStarter

tests:
  servantStarter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servantStarter
